(() => {
"use strict";
const sb=window.supabase.createClient(window.KVK_CONFIG.supabaseUrl,window.KVK_CONFIG.supabaseKey);
const DAYS={monday:{role:"Chief Minister",icon:"🏛️",startDay:"Sunday",startMinute:1425,slotCount:49},tuesday:{role:"Chief Minister",icon:"🏛️",startDay:"Monday",startMinute:1425,slotCount:49},thursday:{role:"Noble Advisor",icon:"👑",startDay:"Wednesday",startMinute:1425,slotCount:49}};
const names=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];let currentDay="monday",admin=null,requests=[],appointments=[],activeSlot=null;const $=id=>document.getElementById(id),esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
function tp(sd,sm,o){let d=names.indexOf(sd),m=sm+o;while(m>=1440){m-=1440;d=(d+1)%7}return{day:names[d],time:`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`}}
function slot(day,i){const c=DAYS[day],s=tp(c.startDay,c.startMinute,i*30),e=tp(c.startDay,c.startMinute,(i+1)*30);let key=`${day}-${i}`;if((day==="monday"&&i===48)||(day==="tuesday"&&i===0))key="chief-crossover";return{key,display:`${s.time}–${e.time}`,full:s.day===e.day?`${s.day} ${s.time}–${e.time}`:`${s.day} ${s.time} → ${e.day} ${e.time}`,cross:s.day!==e.day}}
function apFor(k){return appointments.find(a=>a.slot_key===k)||null}function reqFor(k){return requests.filter(r=>r.slot_key===k&&r.status==="pending")}
async function checkAdmin(){const {data:{session}}=await sb.auth.getSession();if(!session||session.user.is_anonymous)return false;const {data,error}=await sb.from("admin_users").select("admin_role,display_name").eq("id",session.user.id).maybeSingle();if(error||!data)return false;admin=data;return true}
function show(on){$("adminLoginCard").hidden=on;$("adminApp").hidden=!on;$("logoutBtn").hidden=!on;if(on){$("adminName").textContent=admin.display_name||"Admin";$("adminRole").textContent=admin.admin_role.toUpperCase()}}
async function load(){const r=await sb.from("slot_requests").select("id,slot_key,event_day,minister_role,status,profile_id,player_profiles(player_id,player_name,alliance,truegold,general_speedups,research_speedups,training_speedups,construction_speedups)").eq("event_day",currentDay).in("status",["pending","confirmed"]);if(r.error)throw r.error;requests=r.data||[];const a=await sb.from("appointments").select("*").eq("event_day",currentDay);if(a.error)throw a.error;appointments=a.data||[];render()}
function render(){const c=DAYS[currentDay];$("adminRoleTitle").textContent=`${c.icon} ${c.role}`;$("adminCrossoverNote").hidden=currentDay!=="tuesday";const list=$("adminSlotList");list.innerHTML="";let pc=0,cc=0;for(let i=0;i<c.slotCount;i++){const s=slot(currentDay,i),rs=reqFor(s.key),ap=apFor(s.key);pc+=rs.length;if(ap)cc++;const row=document.createElement("div");row.className="slot admin-slot"+(s.cross?" cross":"")+(ap?" confirmed":rs.length?" pending":"");row.innerHTML=`<div class="slot-time">${s.display}</div><div class="slot-main">${ap?`<span class="alliance">${esc(ap.alliance)}</span><strong>${esc(ap.player_name)}</strong>`:rs.length?`<strong>${rs.length} applicant${rs.length===1?"":"s"}</strong>`:`<span class="muted">No requests</span>`}</div><div class="slot-status">${ap?"✓ Confirmed":rs.length?`${rs.length} pending`:""}</div>`;row.onclick=()=>openApplicants(s);list.appendChild(row)}$("adminPendingBadge").textContent=`${pc} pending`;$("adminConfirmedBadge").textContent=`${cc} confirmed`}
function score(r){const p=r.player_profiles||{};if(currentDay==="monday")return(+p.truegold||0)*10+(+p.general_speedups||0)+(+p.construction_speedups||0);if(currentDay==="tuesday")return(+p.truegold||0)*8+(+p.general_speedups||0)+(+p.research_speedups||0)+(+p.construction_speedups||0)*.5;return(+p.general_speedups||0)+(+p.training_speedups||0)+(+p.truegold||0)*2}
function openApplicants(s){activeSlot=s;$("applicantSlotLabel").textContent=`${DAYS[currentDay].role} · ${s.full}`;renderApplicants();$("applicantDialog").showModal()}
function renderApplicants(){const rs=requests.filter(r=>r.slot_key===activeSlot.key&&["pending","confirmed"].includes(r.status)).sort((a,b)=>score(b)-score(a)),box=$("applicantList"),ap=apFor(activeSlot.key);if(!rs.length){box.innerHTML=`<p class="muted">Nobody has requested this slot.</p>`;return}box.innerHTML="";rs.forEach(r=>{const p=r.player_profiles||{},confirmed=ap?.request_id===r.id,d=document.createElement("div");d.className="applicant"+(confirmed?" confirmed":"");d.innerHTML=`<div class="applicant-head"><div><span class="alliance">${esc(p.alliance)}</span> <strong>${esc(p.player_name)}</strong></div><small class="muted">ID ${esc(p.player_id)}</small></div><div class="resource-summary">🏆 ${p.truegold||0} TG · 💨 ${p.general_speedups||0}h general · 📘 ${p.research_speedups||0}h research · ⚔️ ${p.training_speedups||0}h training · 🏗️ ${p.construction_speedups||0}h construction</div><div class="applicant-actions"><button class="primary award">${confirmed?"Confirmed":"Award Slot"}</button><button class="danger reject">Reject</button></div>`;d.querySelector(".award").onclick=()=>award(r.id);d.querySelector(".reject").onclick=()=>reject(r.id);box.appendChild(d)})}
async function award(id){const {error}=await sb.rpc("award_slot",{p_request_id:id});if(error){alert(error.message);return}await load();renderApplicants()}
async function reject(id){const {error}=await sb.from("slot_requests").update({status:"rejected"}).eq("id",id);if(error){alert(error.message);return}await load();renderApplicants()}
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginError").hidden=true;const {error}=await sb.auth.signInWithPassword({email:$("loginEmail").value.trim(),password:$("loginPassword").value});if(error){$("loginError").textContent="Login failed. Check your email/password.";$("loginError").hidden=false;return}if(!(await checkAdmin())){$("loginError").textContent="This account does not have admin access.";$("loginError").hidden=false;return}show(true);await load()};$("logoutBtn").onclick=async()=>{await sb.auth.signOut();show(false)};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll(".day-tab").forEach(b=>b.onclick=async()=>{document.querySelectorAll(".day-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");currentDay=b.dataset.day;await load()});(async()=>{if(await checkAdmin()){show(true);await load()}else show(false)})();
})();