(() => {
"use strict";
const sb=window.supabase.createClient(window.KVK_CONFIG.supabaseUrl,window.KVK_CONFIG.supabaseKey);
const DAYS={
monday:{title:"Monday — City Construction",role:"Chief Minister",icon:"🏛️",startDay:"Sunday",startMinute:1425,slotCount:49,tips:{good:["Truegold","Construction speed up","Intel missions","Master skills"],ok:["Charms","Research speed up"],skip:["Troop speed up","Roulette","Shards","Gather rss","Level up pets","Refinement pets","Forgehammer","Widgets","Mithril","Gov. gear","Master emblem","Manuscript"]}},
tuesday:{title:"Tuesday — Basic Skills",role:"Chief Minister",icon:"🏛️",startDay:"Monday",startMinute:1425,slotCount:49,tips:{good:["Roulette","Shards","Gather rss","Master skills","Master emblem","Manuscript"],ok:["Truegold","Construction speed up","Research speed up"],skip:["Charms","Troop speed up","Intel missions","Level up pets","Refinement pets","Forgehammer","Widgets","Mithril","Gov. gear"]}},
thursday:{title:"Thursday — Hero Development",role:"Noble Advisor",icon:"👑",startDay:"Wednesday",startMinute:1425,slotCount:49,tips:{good:["Charms","Troop speed up","Gather rss"],ok:["Forgehammer","Widgets","Mithril"],skip:["Truegold","Construction speed up","Research speed up","Intel missions","Roulette","Shards","Level up pets","Refinement pets","Gov. gear","Master skills","Master emblem","Manuscript"]}}
};
const names=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
let currentDay="monday",selected=new Set(),user=null,profile=null,appointments=[],myRequests=[];
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
function tp(sd,sm,o){let d=names.indexOf(sd),m=sm+o;while(m>=1440){m-=1440;d=(d+1)%7}return{day:names[d],time:`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`}}
function slot(day,i){const c=DAYS[day],s=tp(c.startDay,c.startMinute,i*30),e=tp(c.startDay,c.startMinute,(i+1)*30);let key=`${day}-${i}`;if((day==="monday"&&i===48)||(day==="tuesday"&&i===0))key="chief-crossover";return{key,day,i,display:`${s.time}–${e.time}`,full:s.day===e.day?`${s.day} ${s.time}–${e.time}`:`${s.day} ${s.time} → ${e.day} ${e.time}`,cross:s.day!==e.day}}
function banner(t,c=""){$("connectionBanner").textContent=t;$("connectionBanner").className=`connection-banner ${c}`}
function tips(){const t=DAYS[currentDay].tips;$("tipsPanel").innerHTML=[["good","✅ GREAT FOR POINTS",t.good],["ok","🟧 OK FOR POINTS",t.ok],["skip","⛔ SKIP TODAY",t.skip]].map(([c,h,a])=>`<div class="tip ${c}"><h4>${h}</h4><div class="chips">${a.map(x=>`<span>${x}</span>`).join("")}</div></div>`).join("")}
function apFor(k){return appointments.find(a=>a.slot_key===k)||null}function mineFor(k){return myRequests.find(r=>r.slot_key===k&&["pending","confirmed"].includes(r.status))||null}
async function ensureAuth(){const {data:{session}}=await sb.auth.getSession();if(session){user=session.user;return}const {data,error}=await sb.auth.signInAnonymously();if(error)throw new Error("Anonymous sign-in is not enabled yet. In Supabase go to Authentication → Sign In / Providers → Anonymous and enable it.");user=data.user}
async function loadProfile(){const {data,error}=await sb.from("player_profiles").select("*").eq("user_id",user.id).maybeSingle();if(error)throw error;profile=data}
async function loadData(){const a=await sb.from("appointments").select("slot_key,event_day,minister_role,player_name,alliance");if(a.error)throw a.error;appointments=a.data||[];if(profile){const r=await sb.from("slot_requests").select("id,slot_key,event_day,minister_role,status").eq("profile_id",profile.id);if(r.error)throw r.error;myRequests=r.data||[]}else myRequests=[]}
function profileUI(){const ok=!!profile;$("profileStatus").textContent=ok?`✓ ${profile.alliance} · ${profile.player_name}`:"Profile required";$("profileStatus").className=`profile-status ${ok?"complete":"incomplete"}`;$("lockedPanel").hidden=ok;$("selectionPanel").hidden=!ok;if(!ok&&!$("profileDialog").open)$("profileDialog").showModal()}
function render(){const c=DAYS[currentDay];tips();$("roleSmall").textContent=c.role;$("roleTitle").textContent=`${c.icon} ${c.role}`;$("crossoverNote").hidden=currentDay!=="tuesday";const list=$("slotList");list.innerHTML="";let confirmed=0;for(let i=0;i<c.slotCount;i++){const s=slot(currentDay,i),ap=apFor(s.key),mine=mineFor(s.key);if(ap)confirmed++;const row=document.createElement("div");row.className="slot"+(s.cross?" cross":"")+(ap?" confirmed":mine?" pending":"")+(selected.has(s.key)?" selected":"");const cb=document.createElement("input");cb.type="checkbox";cb.checked=selected.has(s.key);cb.disabled=!profile||!!ap;cb.onclick=e=>{e.stopPropagation();toggle(s.key)};const t=document.createElement("div");t.className="slot-time";t.textContent=s.display;const main=document.createElement("div");main.className="slot-main";main.innerHTML=ap?`<span class="alliance">${esc(ap.alliance)}</span><strong>${esc(ap.player_name)}</strong>`:mine?`<span class="muted">Your request is pending</span>`:`<span class="muted">Available</span>`;const st=document.createElement("div");st.className="slot-status";st.textContent=ap?"✓ Confirmed":mine?"Pending":"";row.append(cb,t,main,st);row.onclick=()=>{if(profile&&!ap)toggle(s.key)};list.appendChild(row)}$("scheduleSummary").textContent=`${confirmed}/${c.slotCount} confirmed`;$("confirmedBadge").textContent=`${confirmed} confirmed`;const n=selected.size;$("selectionCount").textContent=`${n} of 5 selected`;$("selectionCount").classList.toggle("valid",n>=3&&n<=5);$("submitBtn").disabled=!profile||n<3||n>5;renderMine();profileUI()}
function toggle(k){if(selected.has(k))selected.delete(k);else{if(selected.size>=5){alert("You can select a maximum of 5 slots.");return}selected.add(k)}render()}
function renderMine(){const box=$("myRequests");if(!profile){box.innerHTML=`<p class="muted" style="padding:10px 14px">Complete your profile first.</p>`;return}const rows=myRequests.filter(r=>["pending","confirmed"].includes(r.status));if(!rows.length){box.innerHTML=`<p class="muted" style="padding:10px 14px">No active requests yet.</p>`;return}box.innerHTML=rows.map(r=>{let d=r.slot_key;for(let i=0;i<DAYS[r.event_day].slotCount;i++){const s=slot(r.event_day,i);if(s.key===r.slot_key){d=s.full;break}}return`<div class="request-row"><span class="alliance">${profile.alliance}</span><div><strong>${DAYS[r.event_day].title}</strong><div class="muted">${d} · ${r.minister_role}</div></div><span class="${r.status==="confirmed"?"status-confirmed":"status-pending"}">${r.status==="confirmed"?"✓ Confirmed":"Pending"}</span></div>`}).join("")}
function openProfile(){[$("profileError")].forEach(x=>x.hidden=true);$("playerId").value=profile?.player_id||"";$("playerName").value=profile?.player_name||"";$("alliance").value=profile?.alliance||"KCB";$("truegold").value=profile?.truegold??0;$("general").value=profile?.general_speedups??0;$("research").value=profile?.research_speedups??0;$("training").value=profile?.training_speedups??0;$("construction").value=profile?.construction_speedups??0;$("profileDialog").showModal()}
async function saveProfile(e){e.preventDefault();const err=$("profileError");err.hidden=true;const p={user_id:user.id,player_id:$("playerId").value.trim(),player_name:$("playerName").value.trim(),alliance:$("alliance").value,truegold:+$("truegold").value||0,general_speedups:+$("general").value||0,research_speedups:+$("research").value||0,training_speedups:+$("training").value||0,construction_speedups:+$("construction").value||0};const q=profile?sb.from("player_profiles").update(p).eq("id",profile.id).select().single():sb.from("player_profiles").insert(p).select().single();const {data,error}=await q;if(error){err.textContent=error.message;err.hidden=false;return}profile=data;$("profileDialog").close();await refresh()}
async function submit(){const {error}=await sb.rpc("submit_slot_requests",{p_event_day:currentDay,p_slot_keys:[...selected]});if(error){alert(error.message);return}selected.clear();await refresh();alert("Your slot requests have been saved.")}
async function refresh(){await loadProfile();await loadData();render()}
document.querySelectorAll(".day-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".day-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");currentDay=b.dataset.day;selected.clear();render()});document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).close());$("profileBtn").onclick=openProfile;$("lockedProfileBtn").onclick=openProfile;$("profileForm").onsubmit=saveProfile;$("submitBtn").onclick=submit;$("tipsToggle").onclick=()=>{$("tipsPanel").hidden=!$("tipsPanel").hidden;$("tipsArrow").textContent=$("tipsPanel").hidden?"›":"⌄"};
(async()=>{try{await ensureAuth();await refresh();banner("✓ Connected to the shared KvK planner","ok")}catch(e){console.error(e);banner(e.message,"error")}})();
})();